### ISSUE TITLE
Deprecated GTSAM calls

### ISSUE THREAD

**Issue by ToniRV** [MIT-SPARK/Kimera-RPGO#39]
```
/home/tonirv/Code/RobustPGO/KimeraRPGO/utils/geometry_utils.h:224:28: error: ‘const class gtsam::BetweenFactor<gtsam::Pose3>’ has no member named ‘get_noiseModel’; did you mean ‘noiseModel’?
             between_factor.get_noiseModel())
```
Had to enable `GTSAM_ALLOW_DEPRECATED_SINCE_V4` to fix this issue.
Would be great to move completely to V4 though...

**Comment by Z-Jeff** [comment]
Could you explain how to enable GTSAM_ALLOW_DEPRECATED_SINCE_V4 in detail?
Thank you.

**Comment by yunzc** [comment]
@Z-Jeff I believe we not longer need to enable the `GTSAM_ALLOW_DEPRECATED_SINCE_V4` flag in GTSAM.
