### ISSUE TITLE
Compliation error

### ISSUE THREAD

**Issue by skp1204** [MIT-SPARK/Kimera-RPGO#53]
Compilation of gtsam was successful but running into errors while compiling RPGO module.

[  8%] Building CXX object CMakeFiles/KimeraRPGO.dir/src/RobustSolver.cpp.o
In file included from /home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:31:0,
                 from /home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:19:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h: In member function ‘double KimeraRPGO::PoseWithCovariance<T>::mahalanobis_norm() const’:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:179:61: error: ‘inverse’ is not a member of ‘gtsam’
       return std::sqrt(log.tail(t_dim).transpose() * gtsam::inverse(cov_block) *
                                                             ^~~~~~~
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:179:61: note: suggested alternative:
In file included from /usr/local/include/gtsam/3rdparty/Eigen/Eigen/Core:533:0,
                 from /usr/local/include/gtsam/3rdparty/Eigen/Eigen/Dense:1,
                 from /usr/local/include/gtsam/base/OptionalJacobian.h:22,
                 from /usr/local/include/gtsam/base/Matrix.h:27,
                 from /usr/local/include/gtsam/base/Manifold.h:22,
                 from /usr/local/include/gtsam/base/Lie.h:25,
                 from /usr/local/include/gtsam/base/VectorSpace.h:11,
                 from /usr/local/include/gtsam/geometry/Point2.h:20,
                 from /usr/local/include/gtsam/nonlinear/NonlinearFactorGraph.h:24,
                 from /home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/RobustSolver.h:11,
                 from /home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:6:
/usr/local/include/gtsam/3rdparty/Eigen/Eigen/src/Core/GlobalFunctions.h:59:3: note:   ‘Eigen::inverse’
   EIGEN_ARRAY_DECLARE_GLOBAL_UNARY(inverse,scalar_inverse_op,inverse,\sa ArrayBase::inverse)
   ^
In file included from /home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:31:0,
                 from /home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:19:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:183:47: error: ‘inverse’ is not a member of ‘gtsam’
     return std::sqrt(log.transpose() * gtsam::inverse(covariance_matrix) * log);
                                               ^~~~~~~
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:183:47: note: suggested alternative:
In file included from /usr/local/include/gtsam/3rdparty/Eigen/Eigen/Core:533:0,
                 from /usr/local/include/gtsam/3rdparty/Eigen/Eigen/Dense:1,
                 from /usr/local/include/gtsam/base/OptionalJacobian.h:22,
                 from /usr/local/include/gtsam/base/Matrix.h:27,
                 from /usr/local/include/gtsam/base/Manifold.h:22,
                 from /usr/local/include/gtsam/base/Lie.h:25,
                 from /usr/local/include/gtsam/base/VectorSpace.h:11,
                 from /usr/local/include/gtsam/geometry/Point2.h:20,
                 from /usr/local/include/gtsam/nonlinear/NonlinearFactorGraph.h:24,
                 from /home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/RobustSolver.h:11,
                 from /home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:6:
/usr/local/include/gtsam/3rdparty/Eigen/Eigen/src/Core/GlobalFunctions.h:59:3: note:   ‘Eigen::inverse’
   EIGEN_ARRAY_DECLARE_GLOBAL_UNARY(inverse,scalar_inverse_op,inverse,\sa ArrayBase::inverse)
   ^
In file included from /home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:31:0,
                 from /home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:19:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h: In instantiation of ‘KimeraRPGO::PoseWithNode<T>::PoseWithNode(const gtsam::BetweenFactor<VALUE>&) [with T = gtsam::Pose3]’:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:374:14:   required from ‘void KimeraRPGO::Pcm<poseT, T>::updateOdom(const shared_ptr&, const gtsam::Values&) [with poseT = gtsam::Pose3; T = KimeraRPGO::PoseWithNode; gtsam::NonlinearFactor::shared_ptr = boost::shared_ptr<gtsam::NonlinearFactor>]’
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:166:21:   required from ‘bool KimeraRPGO::Pcm<poseT, T>::removeOutliers(const gtsam::NonlinearFactorGraph&, const gtsam::Values&, gtsam::NonlinearFactorGraph*, gtsam::Values*) [with poseT = gtsam::Pose3; T = KimeraRPGO::PoseWithNode]’
/home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:151:1:   required from here
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:223:28: error: ‘const class gtsam::BetweenFactor<gtsam::Pose3>’ has no member named ‘get_noiseModel’; did you mean ‘noiseModel’?
             between_factor.get_noiseModel())
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
             noiseModel
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:227:15: warning: unused variable ‘dim’ [-Wunused-variable]
     const int dim = getDim<T>();
               ^~~
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:229:15: warning: unused variable ‘t_dim’ [-Wunused-variable]
     const int t_dim = getTranslationDim<T>();
               ^~~~~
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h: In instantiation of ‘KimeraRPGO::PoseWithNode<T>::PoseWithNode(const gtsam::BetweenFactor<VALUE>&) [with T = gtsam::Pose2]’:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:374:14:   required from ‘void KimeraRPGO::Pcm<poseT, T>::updateOdom(const shared_ptr&, const gtsam::Values&) [with poseT = gtsam::Pose2; T = KimeraRPGO::PoseWithNode; gtsam::NonlinearFactor::shared_ptr = boost::shared_ptr<gtsam::NonlinearFactor>]’
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:166:21:   required from ‘bool KimeraRPGO::Pcm<poseT, T>::removeOutliers(const gtsam::NonlinearFactorGraph&, const gtsam::Values&, gtsam::NonlinearFactorGraph*, gtsam::Values*) [with poseT = gtsam::Pose2; T = KimeraRPGO::PoseWithNode]’
/home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:151:1:   required from here
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:223:28: error: ‘const class gtsam::BetweenFactor<gtsam::Pose2>’ has no member named ‘get_noiseModel’; did you mean ‘noiseModel’?
             between_factor.get_noiseModel())
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
             noiseModel
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:227:15: warning: unused variable ‘dim’ [-Wunused-variable]
     const int dim = getDim<T>();
               ^~~
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:229:15: warning: unused variable ‘t_dim’ [-Wunused-variable]
     const int t_dim = getTranslationDim<T>();
               ^~~~~
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h: In instantiation of ‘KimeraRPGO::PoseWithCovariance<T>::PoseWithCovariance(const gtsam::BetweenFactor<VALUE>&) [with T = gtsam::Pose3]’:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:374:14:   required from ‘void KimeraRPGO::Pcm<poseT, T>::updateOdom(const shared_ptr&, const gtsam::Values&) [with poseT = gtsam::Pose3; T = KimeraRPGO::PoseWithCovariance; gtsam::NonlinearFactor::shared_ptr = boost::shared_ptr<gtsam::NonlinearFactor>]’
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:166:21:   required from ‘bool KimeraRPGO::Pcm<poseT, T>::removeOutliers(const gtsam::NonlinearFactorGraph&, const gtsam::Values&, gtsam::NonlinearFactorGraph*, gtsam::Values*) [with poseT = gtsam::Pose3; T = KimeraRPGO::PoseWithCovariance]’
/home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:151:1:   required from here
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:93:28: error: ‘const class gtsam::BetweenFactor<gtsam::Pose3>’ has no member named ‘get_noiseModel’; did you mean ‘noiseModel’?
             between_factor.get_noiseModel())
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
             noiseModel
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h: In instantiation of ‘KimeraRPGO::PoseWithCovariance<T>::PoseWithCovariance(const gtsam::BetweenFactor<VALUE>&) [with T = gtsam::Pose2]’:
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:374:14:   required from ‘void KimeraRPGO::Pcm<poseT, T>::updateOdom(const shared_ptr&, const gtsam::Values&) [with poseT = gtsam::Pose2; T = KimeraRPGO::PoseWithCovariance; gtsam::NonlinearFactor::shared_ptr = boost::shared_ptr<gtsam::NonlinearFactor>]’
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/outlier/pcm.h:166:21:   required from ‘bool KimeraRPGO::Pcm<poseT, T>::removeOutliers(const gtsam::NonlinearFactorGraph&, const gtsam::Values&, gtsam::NonlinearFactorGraph*, gtsam::Values*) [with poseT = gtsam::Pose2; T = KimeraRPGO::PoseWithCovariance]’
/home/kp/workspace/Kimera-RPGO/src/RobustSolver.cpp:151:1:   required from here
/home/kp/workspace/Kimera-RPGO/include/KimeraRPGO/utils/geometry_utils.h:93:28: error: ‘const class gtsam::BetweenFactor<gtsam::Pose2>’ has no member named ‘get_noiseModel’; did you mean ‘noiseModel’?
             between_factor.get_noiseModel())
             ~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
             noiseModel
CMakeFiles/KimeraRPGO.dir/build.make:86: recipe for target 'CMakeFiles/KimeraRPGO.dir/src/RobustSolver.cpp.o' failed
make[2]: *** [CMakeFiles/KimeraRPGO.dir/src/RobustSolver.cpp.o] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/KimeraRPGO.dir/all' failed
make[1]: *** [CMakeFiles/KimeraRPGO.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by yunzc** [comment]
This is a problem cause by the gtsam update. We will get this fixed soon. In the meantime, one way around it is to enable (in gtsam) the flag `GTSAM_ALLOW_DEPRECATED_SINCE_V4`

**Comment by yunzc** [comment]
#54 should fix this issue!
