### ISSUE TITLE
Requesting Guidance for using Kimera-RPGO

### ISSUE THREAD

**Issue by moksh019** [MIT-SPARK/Kimera-RPGO#70]
Hello,
I want to use this amazing RPGO in my project to estimate the pose of my robot. But I'm New in GTSAM and RPGO. Therefore, I'm struggling to install and use this Kimera-RPGO. 
May anyone guide me here?
Thank you.

**Comment by yunzc** [comment]
Sorry for the late reply, but a few good exampled to check out are 

How RPGO is used in Kimera-VIO 
https://github.com/MIT-SPARK/Kimera-VIO/blob/master/src/loopclosure/LoopClosureDetector.cpp#L129 

and also the example script we provided 
https://github.com/MIT-SPARK/Kimera-RPGO/blob/master/examples/RpgoReadG2o.cpp
