### ISSUE TITLE
enum class does work in Apple clang version 11.0.0

### ISSUE THREAD

**Issue by leochan2009** [MIT-SPARK/Kimera-RPGO#71]
hi,
the enum class call doesn't work in clang
https://github.com/MIT-SPARK/Kimera-RPGO/blob/ffb9ed3454f298bcae3293fe57b22e8c003bf16b/src/RobustSolver.cpp#L125
i have to use 
`KimeraRPGO::RobustSolverParams::GncThresholdMode::COST` 
instead.
same for a few other lines.

Thanks

**Comment by yunzc** [comment]
addressed here https://github.com/MIT-SPARK/Kimera-RPGO/pull/72
