### ISSUE TITLE
GncOptimizer.h: No such file or directory

### ISSUE THREAD

**Issue by Z-Jeff** [MIT-SPARK/Kimera-RPGO#75]
When running "catkin build" to build Kimera-PRGO, it occurs an error:
catkin_ws/src/Kimera-RPGO/src/RobustSolver.cpp:16:10: fatal error: gtsam/nonlinear/GncOptimizer.h: No such file or directory
It seems to be "gtsam" version problem, but I have no ideas to solve this.
How can I fix this?
My "gtsam" version is 4.1.0, using Ubuntu20.04 and Ros-Noetic.

**Comment by yunzc** [comment]
Could you try our last tested GTSAM commit `59d902760ea2e2eb407930007439259c0cb62fcf`? In general we try to keep RPGO updated with GTSAM develop.
