### ISSUE TITLE
Unknown hint while running the example

### ISSUE THREAD

**Issue by BIT-TYJ** [MIT-SPARK/Kimera-RPGO#78]
Hello, it is an amazing work!
When I run the command:  ./RpgoReadG2o 3d ../robot_a.g2o 1.0 1.0  ../ v    in  /build,  
the following hint occured: setMaxIterations: changing the max nr of iters might lead to less accurate solutions and is not recommended!   
So how can I get the correct result?

**Comment by yunzc** [comment]
Thank you! The hint shouldn't matter... it is just a default warning from the GNC implementation in GTSAM (from [here](https://github.com/borglab/gtsam/blob/develop/gtsam/nonlinear/GncParams.h#L82)).

**Comment by BIT-TYJ** [comment]
Thank you for your quick reply!
But if I just use the command: ./RpgoReadG2o 3d ../robot_a.g2o 1.0 1.0 ../ v  ,  I only got the warning without optimization result output. 
Then I checked the code of Kimera-RPGO/examples/RpgoReadG2o.cpp and changed the command to : ./RpgoReadG2o 3d ../ordered.g2o 1 1.0 5  ../ v  ,adding <gnc_barc_sq>=5, then I got the result output.
So Are there any requirements for parameters setting? Is it OK to set <pcm_t_simple_thresh> <pcm_R_simple_thresh> <gnc_barc_sq> to 1.0 1.0 and 5 respectively?   
Besides, is GNC module the same as PCM for outlier rejection ?

**Comment by yunzc** [comment]
Sorry for the slow reply.
I see what you mean, yes sorry the examples file instructions was not updated with the rest of the repo, let me make a note to do that. 
It really depends on what you want. GNC is not the same as PCM. While the PCM threshold more intuitively the average error per node, the GNC threshold directly relates to the cost function. Details in this [paper](https://arxiv.org/pdf/1909.08605.pdf). 

My preferred way is to set the GNC threshold as a probability with [this function](https://github.com/MIT-SPARK/Kimera-RPGO/blob/master/include/KimeraRPGO/SolverParams.h#L210) as a confidence threshold from 0~1 since it feels more concrete and the knob you have to tune is just from 0 to 1 (exclusive) with closer to 1 indicating a higher confidence in your loop closure measurements.

**Comment by BIT-TYJ** [comment]
Thank you very much!
If I want to realize multi-robot RPGO，in which the pose graph have discrete odometry edges. This is because the correct transformation matries between&nbsp;
different robots are unknown.&nbsp;&nbsp;
So which command can I use for multi-robot RPGO?

---Original---
From: "Yun ***@***.***&gt;
Date: Sat, Apr 9, 2022 08:21 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MIT-SPARK/Kimera-RPGO] Unknown hint while running the example (Issue #78)




 
Sorry for the slow reply.
 I see what you mean, yes sorry the examples file instructions was not updated with the rest of the repo, let me make a note to do that.
 It really depends on what you want. GNC is not the same as PCM. While the PCM threshold more intuitively the average error per node, the GNC threshold directly relates to the cost function. Details in this paper.
 
My preferred way is to set the GNC threshold as a probability with this function as a confidence threshold from 0~1 since it feels more concrete and the knob you have to tune is just from 0 to 1 (exclusive) with closer to 1 indicating a higher confidence in your loop closure measurements.

**Comment by yunzc** [comment]
Sorry seems like your message is not rendering properly for me... 
![image](https://user-images.githubusercontent.com/18037712/162550363-cf568bf1-8044-4f8b-96d7-b3531763b84b.png)

For multi-robot, this [unit-test](https://github.com/MIT-SPARK/Kimera-RPGO/blob/master/tests/testMultiRobot.cpp#L191) might be a good place to start.

**Comment by BIT-TYJ** [comment]
Thank you! If I want to get results produced by PCM only without GNC，which command can I use?
And I try multi robot PGO with example command，it can work.



---Original---
From: "Yun ***@***.***&gt;
Date: Sat, Apr 9, 2022 09:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MIT-SPARK/Kimera-RPGO] Unknown hint while running the example(Issue #78)




 
Sorry seems like your message is not rendering properly for me...
 
 
For multi-robot, this unit-test might be a good place to start.

**Comment by BIT-TYJ** [comment]
Hello, I have a try to add "params.use_gnc_=false; " at the head of function Simulate() in RpgoReadG2o.cpp, is it a right adjustment for forbidding gnc module but using pcm module only?  
Looking forward to your reply! Thank you!

**Comment by BIT-TYJ** [comment]
Thank you!



---Original---
From: "Yun ***@***.***&gt;
Date: Wed, Apr 13, 2022 21:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MIT-SPARK/Kimera-RPGO] Unknown hint while running the example (Issue #78)




 
Yes that is the right thing to do it you do not want to use GNC. Alternatively, you can also just comment out this line.

**Comment by hhhhhhhh213** [comment]
> 感谢您的快速回复！但是，如果我只是使用命令：./RpgoReadG2o 3d ../robot_a.g2o 1.0 1.0 ../ v，我只收到警告，没有优化结果输出。然后我检查了Kimera-RPGO/examples/RpgoReadG2o.cpp的代码，并将命令更改为：./RpgoReadG2o 3d ../ordered.g2o 1 1.0 5 ../ v ，加 <gnc_barc_sq>=5，然后我得到结果输出。那么参数设置有什么要求吗？是否可以将 <pcm_t_simple_thresh> <pcm_R_simple_thresh> <gnc_barc_sq> 分别设置为 1.0、1.0 和 5？此外，GNC模块是否与PCM相同，用于异常值抑制？

Hello, I encountered the same problem as you, the optimization result has no output, how did you solve it?
 Looking forward to your reply, thank you!

**Comment by BIT-TYJ** [comment]
> > 感谢您的快速回复！但是，如果我只是使用命令：./RpgoReadG2o 3d ../robot_a.g2o 1.0 1.0 ../ v，我只收到警告，没有优化结果输出。然后我检查了Kimera-RPGO/examples/RpgoReadG2o.cpp的代码，并将命令更改为：./RpgoReadG2o 3d ../ordered.g2o 1 1.0 5 ../ v ，加 <gnc_barc_sq>=5，然后我得到结果输出。那么参数设置有什么要求吗？是否可以将 <pcm_t_simple_thresh> <pcm_R_simple_thresh> <gnc_barc_sq> 分别设置为 1.0、1.0 和 5？此外，GNC模块是否与PCM相同，用于异常值抑制？
> 
> Hello, I encountered the same problem as you, the optimization result has no output, how did you solve it? Looking forward to your reply, thank you!

Hello, the parameters should be three, that is "./RpgoReadG2o 3d ../robot_a.g2o 1.0 1.0 1.0 ../ v"   The third parameter should be in 0-1 as explained by the authors above.  Each parameter can be adjusted.

**Comment by hhhhhhhh213** [comment]
Already solved, thank you, I wish you good luck in your studies.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yujie ***@***.***&gt;; 
发送时间: 2023年12月27日(星期三) 晚上10:02
收件人: ***@***.***&gt;; 
抄送: "☞  ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [MIT-SPARK/Kimera-RPGO] Unknown hint while running the example (Issue #78)





   
感谢您的快速回复！但是，如果我只是使用命令：./RpgoReadG2o 3d ../robot_a.g2o 1.0 1.0 ../ v，我只收到警告，没有优化结果输出。然后我检查了Kimera-RPGO/examples/RpgoReadG2o.cpp的代码，并将命令更改为：./RpgoReadG2o 3d ../ordered.g2o 1 1.0 5 ../ v ，加 <gnc_barc_sq&gt;=5，然后我得到结果输出。那么参数设置有什么要求吗？是否可以将 <pcm_t_simple_thresh&gt; <pcm_R_simple_thresh&gt; <gnc_barc_sq&gt; 分别设置为 1.0、1.0 和 5？此外，GNC模块是否与PCM相同，用于异常值抑制？
  
Hello, I encountered the same problem as you, the optimization result has no output, how did you solve it? Looking forward to your reply, thank you!
  
Hello, the parameters should be three, that is "./RpgoReadG2o 3d ../robot_a.g2o 1.0 1.0 1.0 ../ v"   The third parameter should be in 0-1 as explained by the authors above.  Each parameter can be adjusted.
