### ISSUE TITLE
Load more than 1 .g2o files 

### ISSUE THREAD

**Issue by smalltheater** [MIT-SPARK/Kimera-RPGO#81]
Hello author, 
 thank your work for implementation of PCM. I am confused about loading pose graphs. In your testLoadGraph.cpp: https://github.com/MIT-SPARK/Kimera-RPGO/blob/19436dcf7e77ca60b30f96a0e7b1ca3a5408ca0e/tests/testLoadGraph.cpp#L164-L221

you load 2 graphs at the same time. The Key used for loop closure are a1,b1. However, the keys in robot_a.g2o and robot_b.g2o are numbers: https://github.com/MIT-SPARK/Kimera-RPGO/blob/19436dcf7e77ca60b30f96a0e7b1ca3a5408ca0e/tests/data/robot_a.g2o#L1-L6
 The connections between a1 and b1 do not make sense. I think the loop closure should be built with that number keys(6989586621679009794).

**Comment by yunzc** [comment]
Hi, 
This should be correct, the confusion might come from how GTSAM symbol works. https://gtsam.org/doxygen/4.0.0/a03039.html
a is the chr and 1 is the index.
